theme: jekyll-theme-cayman
dashboard:
  title: Pixeebot Activity Dashboard
  metrics:
    - contributions
    - tasks
    - improvement_opportunities
title: PoC .NET - template
description: 🔬 Proof of Concept template repository for .NET
show_downloads: true
